language: java
# Make NetworkTables happy
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - junit4
      - lynx
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - chmod +x gradlew
install: echo "skip 'gradle assemble' step"
script:
  - gradle build --continue

# For CodeCov
after_success:
  - ./gradlew test jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  # For Outputting reports
  # FindBugs
  - if [ -f /home/travis/build/RoboEagles4828/ACE/build/reports/findbugs/main.html ]; then lynx -dump /home/travis/build/RoboEagles4828/ACE/build/reports/findbugs/main.html; fi
  # PMD
  - if [ -f /home/travis/build/RoboEagles4828/ACE/build/reports/pmd/main.html ]; then lynx -dump /home/travis/build/RoboEagles4828/ACE/build/reports/pmd/main.html; fi

jdk:
- oraclejdk8
notifications:
  email: false
  slack: 4828roboeagles:qjpsMMedvSTKBq3KCmDmdAjB
cards:
  enabled:
  - master
  - development
  title: Toast
